### PR TITLE
add Galaxy-E

### PR DESCRIPTION
**Pull request by bgruening**
ping @Alanamosse and @yvanlebras

This PR will ensure that your tools do have a Docker container and a singularity container. planemo-monitor is creating PRs here https://github.com/BioContainers/multi-package-containers and after review you get your container.

This gets important when we really deploy your tools at usegalaxy.eu. As we plan to run everything in Singulairty containers.

ping @erasche as well, just as information.

### CODE REVIEW

**Comment by yvanlebras** [comment]
Hello everyone! Thanks for the ping and initiative! So the idea is that all tools inside the Galaxy-E/tools/ folder from 65MO repo must be ok ? If it's what you mean, I have to clean a little bit some old things but we can do that rapidly! Thank you so much!!!

**Comment by bgruening** [comment]
It always means your tools have to be "clean" ;). Just kidding. This means planemo is looking at your tools daily and extracts the requirement fields to create containers for it. Nothing more. This is ensuring that all your tools do have pre-build containers if someone wants to run your tools in a container and not with conda.

**Comment by yvanlebras** [comment]
ok! Thanks! Just to be sure, you don't have to give the entire https://github.com/65MO/Galaxy-E/tools PATH to planemo? https://github.com/65MO/Galaxy-E is ok ? And... you are not in hollidays normaly ? ???

**Comment by bgruening** [comment]
> ok! Thanks! Just to be sure, you don't have to give the entire https://github.com/65MO/Galaxy-E/tools PATH to planemo?

yes, planemo will search for your tools :)

> And... you are not in hollidays normaly ? ???

I'm on holidays :) But this Galaxy-E thing is exciting!

**Comment by yvanlebras** [comment]
So, sorry for the exciting aspect of this.... !

**Comment by bgruening** [comment]
;) @yvanlebras I probably forget about this one. Can you ping me when you think you are ready?

**Comment by bernt-matthias** [comment]
Ping @yvanlebras should we continue here? I could need one of the tools in the 65MO repo.

- Yes: https://github.com/65MO/Galaxy-E/pull/57 and close https://github.com/65MO/Galaxy-E/pull/56
- No: I would suggest to move the tool to https://github.com/galaxyecology/tools-ecology/

Both are fine for me.

**Pull request closed without merging**
