### PR TITLE
Add workflow4metabolomics tools

### PR DESCRIPTION
**Pull request by lecorguille**
Hi,
I have just gathered a couple of tools in a IUC/devteam like repository [tools-w4m](https://github.com/workflow4metabolomics/tools-w4m)

Until now, we used (I was again) to have one GitHub repository [per tool](https://github.com/workflow4metabolomics). But since your talk @jmchilton at GCC, I believe that merging our tools within one repo can be interesting to get all the cool stuff the community developed.

Before going further in the merging process, I need to convince my collegue :/
Those biocontainers should be a good start!

### CODE REVIEW

**Comment by jmchilton** [comment]
I know it makes a lot of things easier but I'm a bit disappointed to be inadvertently pushing the big repo thing - I like the small repo approach. Thanks for the contribution!

**Comment by lecorguille** [comment]
Hum, I'm not sure to understand ... so you seem to prefere the approach where tools/wrappers are in different GitHub repositories (the inverse of the tool-iuc structure).

If so, can I register more than 20 GitHub repositories in the planemo-monitor list?
Or should I simply use `planemo $PLANEMO_OPTIONS container_register --force_push --recursive "$repo_dir"` in our .travis post process.

Your point of view is interesting and important for us to choose if we should merge our tools in one repo (like tool-iuc) or not.

**Comment by jmchilton** [comment]
> so you seem to prefere the approach where tools/wrappers are in different GitHub repositories (the inverse of the tool-iuc structure).

Yeah - both have value but the fact the IUC uses that model has pushed a lot of tooling and best practices in that direction. My original vision for Planemo and such was for much smaller repositories of tools - I guess I have lost though.

**Comment by lecorguille** [comment]
:)
Thanks you for your feedback.

**Pull request merged**
